databases:
  - name: OpenSeat
    user:
    plan: free

services:
  - type: web
    name: OpenSeat
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "npm install npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: OpenSeat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false