databases:
  - name: OpenSeat
    user:

services:
  - type: web
    name: OpenSeat
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: OpenSeat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false